# -----------------------------
# RUNTIME CONFIGURATION
# -----------------------------

PROJECT_NAME = "AI Cinematic Video Engine"

USE_RANDOM_TOPIC = False
CUSTOM_TOPIC = 'Why The Moon Shines at Night'
UI_MODE = 'DEV'

MAX_SCENES = 2
SHOTS_PER_SCENE = 2
MAX_WORDS_PER_SCENE = 18

OUTPUT_WIDTH = 1280
OUTPUT_HEIGHT = 720
IMAGE_WIDTH = 768
IMAGE_HEIGHT = 432
FPS = 30

FORCE_REGENERATE_IMAGES = False
MIN_SCENE_DURATION = 4
FADE_DURATION = 0.4

ENABLE_HOOK = True
ENABLE_CAPTIONS = True
ENABLE_MUSIC = False
ENABLE_SFX = False
ENABLE_BROLL = True
ENABLE_MOTION = True

CAPTION_MODE = "FAST"
CAPTION_GROUP_SIZE = 3

VIDEO_STYLE = "cinematic"
PROMPT_MAX_WORDS = 55

IMAGE_FOLDER = "images"
AUDIO_FOLDER = "audio"
VIDEO_FOLDER = "videos"
STORY_FILE = "stories/story1.txt"
